- hosts: localhost
  gather_facts: no
  tasks:
  - name: Get secret
    k8s_facts:
      api_version: v1
      kind: Secret
      name: '{{ credentials_name }}'
      namespace: '{{ meta.namespace }}'
    register: secret
  - name: Add switch to group 'switch'
    add_host:
      name: '{{ meta.name }}'
      groups: switch
      ansible_ssh_host: '{{ ip_address }}'
      ansible_ssh_port: '{{ port }}'
      ansible_user: '{{ secret.resources[0].data.username | b64decode }}'
      ansible_password: '{{ secret.resources[0].data.password | b64decode }}'
      ansible_network_os: '{{ network_os }}'

- hosts: switch
  gather_facts: no
  tasks:
  - include_role:
      name: network-runner
      tasks_from: create_vlan
    vars:
      - vlan_id: "{{ vlan_input.id }}"
      - vlan_name: "{{ vlan_input.name }}"
    with_items: "{{ vlans }}"
    loop_control:
      loop_var: vlan_input
    when: vlans is defined
