apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: switches.metal3.io
spec:
  group: metal3.io
  names:
    kind: Switch
    listKind: SwitchList
    plural: switches
    singular: switch
    shortNames:
      - sw
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            ipAddress:
              description: IP Address of the switch
              type: string
            port:
              description: Port to use for SSH connection
              type: integer
              format: int32
              maximum: 65535
              minimum: 1
              default: 22
            networkOS:
              description: The type of OS this switch runs Currently supported
                cumulus, dellos10, eos, junos, nxos, openvswitch
              type: string
            credentialsName:
              description: The name of the secret containing the switch credentials
                (requires keys "username" and "password").
              type: string
            vlans:
              description: Current list of VLANs on the switch
              items:
                properties:
                  id:
                    description: VLAN id
                    format: int32
                    maximum: 4094
                    minimum: 0
                    type: integer
                  name:
                    type: string
                required:
                - id
                type: object
              type: array
          required:
          - ipAddress
          - credentialsName
          - networkOS
          type: object
