apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: switches.metal3.io
spec:
  group: metal3.io
  names:
    kind: Switch
    listKind: SwitchList
    plural: switches
    singular: switch
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
