---
apiVersion: v1
kind: Secret
metadata:
  name: my-switch-secret
type: Opaque
data:
  username: Y3VtdWx1cw==
  password: Q3VtdWx1c0xpbnV4IQ==

---
apiVersion: metal3.io/v1alpha1
kind: Switch
metadata:
  name: example-switch
spec:
  ipAddress: 10.13.57.54
  port: 1401
  credentialsName: my-switch-secret
  vlans:
    - id: 10
      name: test-vlan
